### ISSUE TITLE
[F-Droid] Projection Metadata and Description.

### ISSUE THREAD

**Issue by samtinel** [lloydtorres/stately#17]
As soon as the Crashlytics removal is merged, the last thing to get Stately onto F-Droid is to add the necessary images/metadata/screenshots.
See: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-applications-source-repository
Those additions could be used by @lloydtorres to also publish on the Google play store.
There are two options, namely tripple-T and fastlane. I personally prefer fastlane. 
Since I personally can't access my main dev machine, I can't provide the necessary patches in the next few days. @lloydtorres I couldn't find anything in the repo, do you have some kind of banner already?

**Comment by lloydtorres** [comment]
I can commit the assets I use on Google Play/Amazon Appstore to the repo, assuming they conform to F-Droid's requirements. Is there a reason why you prefer Fastlane over Triple-T?

**Comment by samtinel** [comment]
It boils down to personal preference, but I think fastlane's file structure is more intuitive, as well as it not being part of src/ since it doesn't have anything to do with the app itself but publishing. But the choice  doesn't really matter for F-Droid, especially since both are free software.
In any way, you should take a look at [Fastlane's setup](https://docs.fastlane.tools/getting-started/android/setup/) and [Triple-T's setup](https://github.com/Triple-T/gradle-play-publisher), and decide for yourself since you can then also use it to publish on the play store, meaning one consistent branding and look. What might be interesting that `fastlane supply init` pulls your existing ressources from your play store entry and creates the correct paths already.

**Comment by lloydtorres** [comment]
Thanks, I'll give those a read.

**Comment by lloydtorres** [comment]
Added project metadata to the [`Stately/fastlane/`](https://github.com/lloydtorres/stately/tree/master/Stately/fastlane/metadata/android/en-US) directory. Are there any other client-side changes needed for F-Droid?

If not I can bump up the minor version and we can coordinate publishing on Google Play/Amazon Appstore and F-Droid.

**Comment by samtinel** [comment]
Thank you for the quick action! As far as I can tell, everything should be done now. 
Maybe you can cross check with me, but F-Droid also has guide lines what has to be [included](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) to make it to the "front page". 
The two things which currently aren't included to make it there is the license, but that is afaik not part of fastlane but the metadata I'll create, and 
"at least one of the above translated".
I have created a PR at #19 which translates some stuff to German. 
So if that is merged and the version is bumped, I'll put the metadata up for merging. As soon as it is merged it also takes the build server roughly one to three days max to build it.
It should then appear at: https://f-droid.org/en/packages/com.lloydtorres.stately/
Thank you for your work to make this happen :)

**Comment by lloydtorres** [comment]
> Do you want me to open an issue pointing to the new metadata file before pushing it so you can look over it?

That would be great! Thanks so much for looking into this.

Resolving this issue for now, we can track further work in that new issue.
