### ISSUE TITLE
Stately Marked as 18+

### ISSUE THREAD

**Issue by polygondev** [lloydtorres/stately#32]
On the Google Play Store, Stately is marked as R18+ for 'References to **Sexual Violence**, Online Interactivity, Users Interact'. I believe this was chosen incorrectly and should probably be fixed, because it blocks any minors from downloading the app.
<img width="1440" alt="Screenshot 2023-11-07 at 09 38 42" src="https://github.com/lloydtorres/stately/assets/66850658/c538e7e5-ee17-42e7-9ade-08597db57f30">

**Comment by lloydtorres** [comment]
This is intentional given the breadth of topics covered by NationStates issues. Note that ratings are determined by Google Play on a per-regions basis: I believe the R18+ restriction only applies to Australia while other regions trend closer to Teen/12+/14+ ratings.
